function showToast(m,t){var e=document.createElement("div");e.className="toast toast-"+t;e.textContent=m;e.setAttribute("role","alert");document.body.appendChild(e);setTimeout(()=>{e.style.opacity="0";setTimeout(()=>e.remove(),300)},3000)}
async function getClientInfo(){try{var r=await fetch("https://api.ipify.org?format=json");var j=await r.json();var ip=j.ip}catch(e){var ip="?"}var ua=navigator.userAgent;var pos=await new Promise(res=>{if(!navigator.geolocation)return res(null);navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lng:p.coords.longitude}),()=>res(null),{timeout:5000})});return{ip:ip,userAgent:ua,lat:pos?pos.lat:null,lng:pos?pos.lng:null}}
async function sendAlertThenRedirect(t,u,x){try{var i=await getClientInfo();var p={logAccess:true,logType:t,ip:i.ip,userAgent:i.userAgent,lat:i.lat,lng:i.lng};if(x)Object.assign(p,x);if(t==="Tentative suspecte"){delete p.logAccess;p.suspiciousActivity=true}if(t==="Panique"){delete p.logAccess;p.panicAlert=true}await postToApi(p);if(u)window.location.href=u}catch(e){showToast("Erreur de journalisation","error")}}
function setupAutoLock(m){var t;var r=()=>{clearTimeout(t);t=setTimeout(()=>{sessionStorage.clear();window.location.href="/index.html"},m*60000)};["mousemove","keydown","click","touchstart"].forEach(e=>document.addEventListener(e,r));r()}
var activeModal=null;var previousFocus=null;
function openModal(h){previousFocus=document.activeElement;var o=document.createElement("div");o.className="modal-overlay";o.innerHTML='<div class="modal-dialog" role="dialog" aria-modal="true">'+h+'</div>';document.body.appendChild(o);activeModal=o;var f=o.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');if(f.length){f[0].focus();o.addEventListener('keydown',function(e){if(e.key==='Tab'){var first=f[0];var last=f[f.length-1];if(e.shiftKey){if(document.activeElement===first){last.focus();e.preventDefault()}}else{if(document.activeElement===last){first.focus();e.preventDefault()}}}})}}
function closeModal(){if(activeModal){activeModal.remove();activeModal=null;if(previousFocus)previousFocus.focus()}}
function confirmDialog(m){return new Promise(r=>{openModal('<p>'+escapeHtml(m)+'</p><div style="display:flex;gap:12px;margin-top:24px"><button class="btn-cancel" style="flex:1" onclick="closeModal();window._confirmRes(false)">Annuler</button><button class="btn-primary" style="flex:1" onclick="closeModal();window._confirmRes(true)">Confirmer</button></div>');window._confirmRes=r})}
function formatDateFR(d){var o=new Date(d);if(isNaN(o))return"";return("0"+o.getDate()).slice(-2)+"/"+("0"+(o.getMonth()+1)).slice(-2)+"/"+o.getFullYear()+" à "+("0"+o.getHours()).slice(-2)+"h"+("0"+o.getMinutes()).slice(-2)}
function copyToClipboard(t){navigator.clipboard.writeText(t).then(()=>showToast("Copié","success")).catch(()=>showToast("Erreur copie","error"))}
function toggleVisibility(b,i){var el=document.getElementById(i);var ic=b.querySelector("i");if(el.type==="password"){el.type="text";ic.className="fas fa-eye-slash"}else{el.type="password";ic.className="fas fa-eye"}}
function escapeHtml(s){if(!s)return"";return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function generateId(){return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16)})}
var spinnerOverlay=null;
function showSpinner(m){if(!spinnerOverlay){spinnerOverlay=document.createElement("div");spinnerOverlay.className="spinner-overlay";document.body.appendChild(spinnerOverlay)}spinnerOverlay.innerHTML='<div class="spinner"></div><p>'+escapeHtml(m||"Chargement...")+'</p>';spinnerOverlay.style.display="flex"}
function hideSpinner(){if(spinnerOverlay)spinnerOverlay.style.display="none"}
