function showToast(m,t){var c=document.getElementById('toast-container');if(!c){c=document.createElement('div');c.id='toast-container';c.style.cssText='position:fixed;bottom:20px;right:20px;z-index:9999;display:flex;flex-direction:column;gap:10px;';document.body.appendChild(c);}var b=document.createElement('div');b.className='toast '+t;b.style.cssText='padding:12px 20px;border-radius:6px;color:#fff;font-weight:500;box-shadow:0 4px 12px rgba(0,0,0,0.5);opacity:0;transition:opacity 0.3s ease;';if(t==='error')b.style.backgroundColor='#e63946';else if(t==='success')b.style.backgroundColor='#06d6a0';else b.style.backgroundColor='#457b9d';b.textContent=m;c.appendChild(b);setTimeout(()=>{b.style.opacity='1';},10);setTimeout(()=>{b.style.opacity='0';setTimeout(()=>{b.remove();},300);},3000);}
async function getClientInfo(){var r={ip:'Inconnue',userAgent:navigator.userAgent,lat:null,lng:null};try{var a=await fetch('https://api.ipify.org?format=json');var i=await a.json();r.ip=i.ip;}catch(e){}try{if(navigator.geolocation){var p=await new Promise((res,rej)=>{navigator.geolocation.getCurrentPosition(res,rej,{timeout:5000});});r.lat=p.coords.latitude;r.lng=p.coords.longitude;}}catch(e){}return r;}
function setupAutoLock(m,u){var t;var r=function(){clearTimeout(t);t=setTimeout(()=>{sessionStorage.clear();window.location.href=u;},m*60000);};['mousemove','keydown','touchstart','click'].forEach(e=>document.addEventListener(e,r));r();}
function openModal(id){var m=document.getElementById(id);if(m)m.style.display='flex';}
function closeModal(id){var m=document.getElementById(id);if(m)m.style.display='none';}
function confirmDialog(m){return new Promise((res)=>{var c=document.createElement('div');c.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.8);display:flex;align-items:center;justify-content:center;z-index:10000;';var b=document.createElement('div');b.style.cssText='background:#1a1a2e;padding:20px;border-radius:8px;max-width:400px;text-align:center;color:#fff;box-shadow:0 4px 12px rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.1);';var p=document.createElement('p');p.textContent=m;p.style.marginBottom='20px';b.appendChild(p);var btns=document.createElement('div');btns.style.cssText='display:flex;gap:10px;justify-content:center;';var y=document.createElement('button');y.textContent='Oui';y.style.cssText='padding:8px 16px;background:#e63946;color:#fff;border:none;border-radius:4px;cursor:pointer;';var n=document.createElement('button');n.textContent='Non';n.style.cssText='padding:8px 16px;background:rgba(255,255,255,0.1);color:#fff;border:none;border-radius:4px;cursor:pointer;';btns.appendChild(n);btns.appendChild(y);b.appendChild(btns);c.appendChild(b);document.body.appendChild(c);y.onclick=()=>{c.remove();res(true);};n.onclick=()=>{c.remove();res(false);};});}
function formatDateFR(d){var o=new Date(d);var j=('0'+o.getDate()).slice(-2);var m=('0'+(o.getMonth()+1)).slice(-2);var a=o.getFullYear();var h=('0'+o.getHours()).slice(-2);var mn=('0'+o.getMinutes()).slice(-2);return j+'/'+m+'/'+a+' à '+h+'h'+mn;}
function copyToClipboard(t){var i=document.createElement('input');i.value=t;document.body.appendChild(i);i.select();document.execCommand('copy');document.body.removeChild(i);showToast('Copié dans le presse-papier','success');}
function toggleVisibility(id,iId){var e=document.getElementById(id);var i=document.getElementById(iId);if(e.type==='password'){e.type='text';i.className='fas fa-eye-slash';}else{e.type='password';i.className='fas fa-eye';}}
function escapeHtml(u){return String(u).replace(/[&<>"'`=\/]/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;','/':'&#x2F;','`':'&#x60;','=':'&#x3D;'}[s];});}