function showToast(m,t){var c=document.getElementById('toast-container');if(!c){c=document.createElement('div');c.id='toast-container';document.body.appendChild(c);}var e=document.createElement('div');e.className='toast toast-'+(t||'info');e.textContent=m;c.appendChild(e);setTimeout(function(){e.classList.add('fade-out');setTimeout(function(){e.remove();},300);},3000);}
async function getClientInfo(){var i={ip:'?',userAgent:navigator.userAgent,lat:null,lng:null};try{var r=await fetch('https://api.ipify.org?format=json');var d=await r.json();i.ip=d.ip;}catch(e){}try{var p=await new Promise(function(res,rej){navigator.geolocation.getCurrentPosition(res,rej,{timeout:5000});});i.lat=p.coords.latitude;i.lng=p.coords.longitude;}catch(e){}return i;}
function setupAutoLock(m){var t;function r(){clearTimeout(t);t=setTimeout(function(){sessionStorage.clear();window.location.href='index.html';},m*60000);}['mousemove','keydown','scroll','click'].forEach(function(e){document.addEventListener(e,r);});r();}
function openModal(h){var m=document.getElementById('app-modal');if(!m){m=document.createElement('div');m.id='app-modal';m.className='modal-overlay';document.body.appendChild(m);}m.innerHTML='<div class="modal-content"><button class="modal-close" onclick="closeModal()"><i class="fas fa-times"></i></button>'+h+'</div>';m.style.display='flex';}
function closeModal(){var m=document.getElementById('app-modal');if(m)m.style.display='none';}
function confirmDialog(m){return new Promise(function(res){var html='<div class="confirm-dialog"><p>'+escapeHtml(m)+'</p><div class="confirm-actions"><button id="confirm-cancel" class="btn btn-secondary">Annuler</button><button id="confirm-ok" class="btn btn-danger">Confirmer</button></div></div>';openModal(html);document.getElementById('confirm-cancel').onclick=function(){closeModal();res(false);};document.getElementById('confirm-ok').onclick=function(){closeModal();res(true);};});}
function formatDateFR(d){if(!d)return'';var o=new Date(d);return('0'+o.getDate()).slice(-2)+'/'+('0'+(o.getMonth()+1)).slice(-2)+'/'+o.getFullYear();}
async function copyToClipboard(t){try{await navigator.clipboard.writeText(t);showToast('Copié','success');}catch(e){showToast('Erreur copie','error');}}
function toggleVisibility(b,i){var f=document.getElementById(i);var ic=b.querySelector('i');if(f.type==='password'){f.type='text';if(ic){ic.classList.remove('fa-eye');ic.classList.add('fa-eye-slash');}}else{f.type='password';if(ic){ic.classList.remove('fa-eye-slash');ic.classList.add('fa-eye');}}}
function escapeHtml(s){if(typeof s!=='string')return s;return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}